// "use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NextAuthProvider from "./components/Provider";
import { Logout, NavLogin } from "./components/Button";

import Image from "next/image";
import { getServerSession } from "next-auth";
import { authOptions } from "./config/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reza Realtime Chat App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <nav className="flex px-10 py-5 justify-between fixed top-0 left-0 w-full bg-white">
            <h1 className=" text-3xl font-bold text-[#131116]">
              Reza<span className="text-rose-700">Chat</span>
            </h1>

            {session ? (
              <div className="flex items-center">
                <Image
                  src={session.user?.image as string}
                  alt="user profile photo"
                  className="w-12 h-12 rounded-full mr-3"
                  width={50}
                  height={50}
                />
                <Logout />
              </div>
            ) : (
              <NavLogin />
              // <></>
            )}
          </nav>
          <main>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
